fragment ProductBase on Product {
    id
    categories {
        id
        name
    }
    description
    images {
        id
        alt
        height
        url
        width
    }
    name
    price
    rating
}

fragment ProductReview on Review {
    author
    createdAt
    description
    email
    id
    rating
    title
}