query HomePage($take: Int!, $skip: Int!) {
    collections {
        data {
            id
            description
            name
            products {
                id
                images {
                    id
                    alt
                    height
                    url
                    width
                }
            }
            slug
        }
    }
    products(take: $take, skip: $skip) {
        data {
            ...ProductBase
        }
    }
}