query ProductsPageList($take: Int, $skip: Int, $orderBy: ProductSortBy) {
    products(take: $take, skip: $skip, orderBy: $orderBy) {
        data {
            ...ProductBase
        }
        meta {
            total
        }
    }
}