query ProductById($id: ID!) {
    product(id: $id) {
        ...ProductBase
    }
}

query RelatedProducts {
    products(take: 5) {
        data {
            ...ProductBase
        }
    }
}

query ProductReviews($id: ID!) {
    product(id: $id) {
        id
        reviews {
            ...ProductReview
        }
    }
}